# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "/home/otterdev_ball/BaseDiskProject/rust_project/fete_des_gourmets/Fete-des-gourmets/fete_des_gourmets/src/infrastructure/sqlite/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/home/otterdev_ball/BaseDiskProject/rust_project/fete_des_gourmets/Fete-des-gourmets/fete_des_gourmets/src/infrastructure/sqlite/migrations"
